### ISSUE TITLE
Using scrollToIndex with a grouped list will scroll the list to the group instead of the item

### ISSUE THREAD

**Issue by kirillkurko** [inokawa/virtua#241] opened 2023-11-02 12:13 UTC
**Describe the bug**
When using [Sticky example](https://inokawa.github.io/virtua/?path=/story/basics-vlist--sticky) and trying to add scroll to index behavior, I noticed a problem - it scrolls to the group at the specified index, not to the element.

**To Reproduce**
Here is the component that reproduces the problem: 
```tsx
const StickyList: React.FC<{ initialItemIndex?: number }> = ({ initialItemIndex }) => {
  const listRef = useRef<VListHandle | null>(null);
  const [scrollToIndexEnabled, setScrollToIndexEnabled] = useState(true);

  useEffect(() => {
    if (scrollToIndexEnabled && initialItemIndex !== undefined) {
      listRef.current.scrollToIndex(initialItemIndex);
      setScrollToIndexEnabled(false);
    }
  }, [scrollToIndexEnabled, initialItemIndex]);

  return (
    <VList ref={listRef} style={{ height: "100vh" }} overscan={1}>
      {Array.from({ length: 100 }).map((_, i) => {
        return (
          <div
            key={i}
            style={{
              borderBottom: "solid 1px #ccc",
            }}
          >
            {Array.from({ length: 10 }).map((_, j) => {
              const isGroupTop = j === 0;
              return (
                <div
                  key={j}
                  style={{
                    height: 60,
                    background: "#fff",
                    ...(isGroupTop && {
                      top: 0,
                      height: 30,
                      position: "sticky",
                      borderBottom: "solid 1px #ccc",
                    }),
                  }}
                >
                  {isGroupTop ? i : `${i} - ${j}`}
                </div>
              );
            })}
          </div>
        );
      })}
    </VList>
  );
}
```

When using the component above like this:
```tsx
<StickyList initialItemIndex={10} />
```

I expect the list to scroll to the element at index 10, but the current behavior is that it will scroll to group 10.

**Expected behavior**
`scrollToIndex` must go to the element at the specified index and not to the group.

**Platform:**

- OS: MacOS
- Browser: Chrome
- Version of react: 18.2.0
- Version of this package: 0.16.0

**Additional context**
I was able to get around this problem by calculating the required offset and using the `scrollTo` function

**Comment by inokawa** [comment] 2023-11-02 12:40
Hi, it's intended behavior and not a bug.
You passed 10 items to VList so you can choose one of them by scrollToIndex.

However I also think there is room for improvement for sticky usage or grouped list.
I'll try to add API for it.

**Comment by kirill-cloudwall** [comment] 2023-11-02 13:04
Yes, that's fair, it's not a bug, but the way things are implemented. Based on experience with creating virtualized grouped sticky lists, `scrollToIndex` always scrolls to the element's index, and the layout (elements nested in groups nested in a list component) is more of an implementation detail.

I don't mind leaving it as is because once you know the index you can calculate the offset, but maybe we need to explain the behavior of `scrollToIndex` better then

**Comment by kirillkurko** [comment] 2023-11-02 13:06
Yes, that's fair, it's not a bug, but the way things are implemented. Based on experience with creating virtualized grouped sticky lists, `scrollToIndex` always scrolls to the element's index, and the layout (elements nested in groups nested in a list component) is more of an implementation detail.

I don't mind leaving it as is because once you know the index you can calculate the offset, but maybe we need to explain the behavior of `scrollToIndex` better then

**Comment by kirillkurko** [comment] 2023-11-03 18:01
@inokawa, would it be possible to enable discussions for this repository? I have some generic feedback and I think the discussions would be a great place to share it. If you have other options in mind, please let me know

**Comment by inokawa** [comment] 2023-11-04 02:05
@kirillkurko 
I enabled discussions!

**Comment by kirillkurko** [comment] 2023-11-06 08:57
Thanks, I'll share the feedback later this week!

**Comment by inokawa** [comment] 2023-12-23 12:29
Duplicate of #278

**Closed by inokawa** 2023-12-23 12:29 UTC
