### ISSUE TITLE
Feature request: useVirtualizer composable

### ISSUE THREAD

**Issue by zernonia** [inokawa/virtua#388] opened 2024-02-20 05:36 UTC
**Is your feature request related to a problem? Please describe.**
I love how small and flexible the package is, and would like to use it to build `Virtualizer` and `ListItem` component for radix-vue.

Currently there's no core functionalities being exported other than `React`, `Vue`, or `Solid` component.  

**Describe the solution you'd like**
Expose `createScroller`, `createResizer` and other core function

**Describe alternatives you've considered**
Or, create a virtualizer composable similar to [TanStack Virtualizer](https://tanstack.com/virtual/latest/docs/introduction#the-virtualizer)

**Comment by inokawa** [comment] 2024-02-20 06:21
Hello,
I'd like to increase customizability of this package. However I'm also cautious to expose core because internal APIs are not stable and they can induce misuse of this package.

I can add lacking features for you if they are reasonable.
Or it may be OK to expose core with prefix like `import { unstable_createScroller, unstable_createResizer } from 'virtua/core;`, and tell use them at your own risk. One of the reason why this package is small is that we compress internal APIs as much as possible, so it can increase bundle size somewhat.

**Comment by zernonia** [comment] 2024-02-20 09:36
Thanks for your swift response @inokawa . I understand your concern. Exposing unstable function might not be ideal for now. 
 
Perhaps I can rename this ticket to "feature request: useVirtualizer"? This way whoever interested with the composition could react '👍🏻' as a gauge for feature demand, and you can slowly work towards stabilizing codebase? 😁

**Comment by inokawa** [comment] 2024-02-20 10:15
Yes. No problem!

I'm not sure tanstack like approach is the best, but anyway I agree with that packed `useVirtualizer` like function would be needed because in some case we want to display items in different algorithm (ex. table tag #312 ).

**Comment by inokawa** [comment] 2024-11-30 02:40
Duplicate of #428

**Closed by inokawa** 2024-11-30 02:40 UTC
