### ISSUE TITLE
VList horizontal scrollOffset is not updating in iOS Safari

### ISSUE THREAD

**Issue by feketegy** [inokawa/virtua#257] opened 2023-11-26 09:01 UTC
**Describe the bug**

iOS Safari doesn't seem to have a continuous event trigger for scrolling an element. The event chain on iOS is something like `touch start (triggered) --> movement (no event) --> touch end (triggered)` therefore the scroll event is only updated at the end of the interaction.

**To Reproduce**

1. Create a `<VList horizontal .../>` component and scroll the element left to right in iOS Safari.
2. The `scrollOffset` property is only updated when the scrolling stops.

**Expected behavior**

Similar behavior as in other browsers. A continous update of the `scrollOffset` property when scrolling.

**Platform:**

- OS: iOS
- Browser: [Safari
- Version of react: 18.2.0
- Version of this package: 0.15.7

**Comment by inokawa** [comment] 2023-11-26 09:06
@feketegy 
Hi, could you tell me the version of iOS Safari you tested?

**Comment by feketegy** [comment] 2023-11-26 09:18
@inokawa sure, iOS 17.0.1 and the full user agent for Safari on iOS is `Mozilla/5.0 (iPhone; CPU iPhone OS 17_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1
browser`

**Comment by inokawa** [comment] 2023-11-26 09:22
Thanks!
It look like similar version to my iOS... I might be misunderstanding something but anyway I try to reproduce it.

**Comment by inokawa** [comment] 2023-11-26 09:53
@feketegy 
So could I ask you what the actual problem is?
Virtualization fails? or you want to use VListHandle.scrollOffset for something?

If your request is that VList should have same timing to dispatch scroll events across browsers, I think it's impossible because each browsers have different timing and VList just subscribes it.

If iOS Safari dispatches scroll event but VList missed it, it should be fixed.
If virtualization fails due to wrong logic of VList, it should be fixed.

**Comment by feketegy** [comment] 2023-11-26 10:23
You're right, it's more of an issue in iOS and scrolling than with the package.

On touch devices there's no real scrolling happening, instead touch swipe and movement.

Other virtualized list packages fix this by calculating the distance moved in the touch event and updating the scroll property with that value, to have a consistent functionality across browsers. I thought virtua handles it the same way.

**Comment by inokawa** [comment] 2023-11-26 10:52
Do you know what library supports fallback with touch event?
If it's acceptable one, it's worth to implement it for virtua also.

**Comment by feketegy** [comment] 2023-11-26 10:54
If I remember correctly `react-virtualized` and `react-window` do it.

**Comment by inokawa** [comment] 2023-11-26 10:59
Thanks!

As far as I know, they doesn't subscribe touch event but it has `WebkitOverflowScrolling: 'touch'` style on scrollable element.
It may solve your problem if you migrated from react-virtualized or react-window.
 
https://github.com/bvaughn/react-window/blob/efad3d8909753fd74aad7c47dc902b26f0919651/src/createListComponent.js#L374

**Closed** 2023-12-03 01:37 UTC
