### ISSUE TITLE
Importing issue after upgrading from 0.23.3 to 0.24.0

### ISSUE THREAD

**Issue by jesspinklet** [inokawa/virtua#365] opened 2024-02-06 16:10 UTC
First of all, thanks for this amazing package, been looking for something this for Vue 3 or even pure JS.

**Describe the bug**
I'm use Nuxt 3 which uses Vue 3.

Just like I said in title, I can't import the components after upgrading. it throws error.
`import { Virtualizer, VList } from 'virtua/vue'`

**Comment by inokawa** [comment] 2024-02-07 01:03
Hi, could you show me the detailed error?

**Comment by inokawa** [comment] 2024-02-11 13:09
Closing because it was not reproduced.
Feel free to reopen it if you have any additional information or reproduction.

**Closed by inokawa** 2024-02-11 13:09 UTC
